import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@/app/_ui/globals.css';
import Navbar from '@/app/_ui/components/navbar';

const geistSans = localFont({
  src: './_ui/fonts/GeistVF.woff',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
